

export enum OrderStatus {

  PENDIENTE = 'PENDIENTE',
  REVISION = 'REVISION',
  CONFIRMADO = 'CONFIRMADO',
  CANCELADO = 'CANCELADO',
  REPARACION = 'REPARACION',
  FINALIZADO = 'FINALIZADO',
  PAGO = "PAGO",
  RETIRADO = "RETIRADO",
  
}
